import { Poppins } from "next/font/google";
import "./globals.css";

// Import Poppins for English content
const poppins = Poppins({
  subsets: ["latin"], // Correct subset for English (Latin script)
  weight: ["400", "700"], // Specify weights as needed
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} text-slate-800 bg-[#f0eded] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
